# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='LinkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('post_date', models.DateField()),
                ('approved', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='approver',
            name='to_approve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autofeed_plugin.LinkPost'),
        ),
    ]
