# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autofeed_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linkpost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
