# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPLoger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='time stamp of post')),
                ('httpStuff', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
