# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTRToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('JWTtoken', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='httploger',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
