# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssbot', '0002_auto_20161118_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skypeid', models.CharField(max_length=100)),
                ('username', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
