# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssbot', '0003_userids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userids',
            name='skypeid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userids',
            name='username',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
